import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'dashboard': 'Dashboard',
          'users': 'Users',
          'doctors': 'Doctors',
          'blood': 'Blood',
          'settings': 'Settings',
          'yearly': 'Yearly',
          'bloodTypeDistribution': 'Blood Type Distribution',
          'bloodStaff': 'Blood Staff',
          'yearlyDonations': 'Yearly Donations',
          'monthlyDonations': 'Monthly Donations',
          'weeklyDonations': 'Weekly Donations',
          'dailyDonations': 'Daily Donations',
          'totalUsers': 'Total Users',
          'totalDoctors': 'Total Doctors',
          'totalStations': 'Total Stations',
          'newUsers': 'New Users',
          'usersJoining': 'Users Joining',
          'doctorsJoining': 'Doctors Joining',
          'stationAddress': 'Station Address',
          'examinerName': 'Examiner Name',
          'quantity': 'Quantity',
          'bloodType': 'Blood Type',
          'generate': 'Generate',
          'usersBetween18And25': 'Users Between 18 And 25',
          'usersBetween25And50': 'Users Between 25 And 50',
          'usersAbove50': 'Users Above 50',
          'from': 'From',
          'to': 'To',
          'viewReport': 'View Report',
          'name': 'Name',
          'phone': 'Phone',
          'address': 'Address',
          'specialization': 'Specialization',
          'rate': 'Rate',
          'workingDays': 'Working Days',
          'startHour': 'Start Hour',
          'endHour': 'End Hour',
          'joinDate': 'Join Date',
          'addDoctor': 'Add Doctor',
          'login': 'Login',
          'register': 'Register',
          'username': 'Username',
          'password': 'Password',
          'confirmPassword': 'Confirm Password',
          'fullName': 'Full Name',
          'email': 'Username',
          'points': 'Points',
          'usersFound': 'Users Found',
          'allUsers': 'All Users',
          'age': 'Age',
          'height': 'Height',
          'applicationInfo': 'Application Info',
          'facebook': 'Facebook',
          'website': 'Website',
          'version': 'Version',
          'createStation': 'Create Station',
          'stationName': 'Station Name',
          'adminId': 'Admin ID',
          'delete': 'Delete',
          'confirm_deletion': 'Confirm deletion',
          'doctor_details': 'Doctor Details',
          'delete_doctor_confirm': 'Are You Sure About Doctor Deletion',
          'delete_user_confirm': 'Are You Sure About User Deletion',
          'cancel': 'Cancel',
          'location': 'Location',
        },
        'ar': {
          'dashboard': 'لوحة القيادة',
          'users': 'المستخدمون',
          'doctors': 'الأطباء',
          'blood': 'الدم',
          'settings': 'الإعدادات',
          'yearly': 'سنوي',
          'bloodTypeDistribution': 'توزيع فصائل الدم',
          'bloodStaff': 'تبرعات بالدم',
          'yearlyDonations': 'التبرعات السنوية',
          'monthlyDonations': 'التبرعات الشهرية',
          'weeklyDonations': 'التبرعات الأسبوعية',
          'dailyDonations': 'التبرعات اليومية',
          'stationAddress': 'عنوان المحطة',
          'examinerName': 'اسم الفاحص',
          'quantity': 'الكمية',
          'bloodType': 'فصيلة الدم',
          'generate': 'توليد',
          'usersBetween18And25': 'المستخدمون بين 18 و 25',
          'usersBetween25And50': 'المستخدمون بين 25 و 50',
          'usersAbove50': 'المستخدمون فوق 50',
          'from': 'من',
          'to': 'إلى',
          'viewReport': 'عرض التقرير',
          'name': 'الاسم',
          'phone': 'رقم الهاتف',
          'address': 'العنوان',
          'specialization': 'التخصص',
          'rate': 'التقييم',
          'workingDays': 'أيام العمل',
          'startHour': 'ساعة البدء',
          'endHour': 'ساعة الانتهاء',
          'joinDate': 'تاريخ الانضمام',
          'addDoctor': 'إضافة طبيب',
          'login': 'تسجيل الدخول',
          'register': 'تسجيل',
          'username': 'اسم المستخدم',
          'password': 'كلمة المرور',
          'confirmPassword': 'تأكيد كلمة المرور',
          'fullName': 'الاسم الكامل',
          'email': 'أسم المستخدم',
          'points': 'النقاط',
          'usersFound': 'عدد المستخدمين',
          'allUsers': 'كل المستخدمين',
          'age': 'العمر',
          'height': 'الطول',
          'applicationInfo': 'معلومات التطبيق',
          'facebook': 'فيسبوك',
          'website': 'الموقع الإلكتروني',
          'version': 'الإصدار',
          'createStation': 'إنشاء محطة',
          'stationName': 'اسم المحطة',
          'adminId': 'معرف المسؤول',
          'location': 'الموقع',
          'totalUsers': 'إجمالي المستخدمين',
          'totalDoctors': 'إجمالي الأطباء',
          'totalStations': 'إجمالي المحطات',
          'newUsers': 'المستخدمين الجدد',
          'usersJoining': 'المستخدمين الذين انضموا',
          'delete': 'حذف',
          'delete_doctor_confirm': 'هل انت متأكد من حذف الطبيب',
          'delete_user_confirm': 'هل انت متأكد من حذف المستخدم',
          'cancel': 'إلغاء',
          'confirm_deletion': 'تأكيد الحذف',
          'doctor_details': 'تفاصيل الطبيب',
          'doctorsJoining': 'الأطباء الذين انضموا'
        },
      };
}
